//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackDiscount
    {
        public int IdBackDiscount { get; set; }
        public Nullable<int> DiscountPercent { get; set; }
    }
}
