//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CallShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class FixingAct
    {
        public int IdAct { get; set; }
        public Nullable<int> IdClient { get; set; }
        public string IdPhone { get; set; }
        public Nullable<int> IdRepair { get; set; }
        public Nullable<int> IdMaterial { get; set; }
    
        public virtual Client Client { get; set; }
        public virtual MaterialList MaterialList { get; set; }
        public virtual Phone Phone { get; set; }
        public virtual RepairType RepairType { get; set; }
    }
}
